# -*- python -*-
Import("env")
import sys

env.Program(["CFHT2MaskedImage.cc"], LIBS=env.getlibs("imageproc"))

import lsst.tests

import lsst.SConsUtils as scons         # scons 1.17 supports "env.ProductDir", but for now use scons.ProductDir
dataDir = scons.ProductDir("fwData")
args = dict([
    ("CFHT2MaskedImage", "%s/871034p_1 %s/871034p_1_MI" % (dataDir, dataDir)),
    ])
#
# Tests
#
if dataDir:
    ignoreList = None
else:
    print >> sys.stderr, "fwData is not set up; skipping tests requiring data"
    ignoreList = args.keys()

tests = lsst.tests.Control(env, args=args, ignoreList=ignoreList, verbose=True)
tests.run("*.cc")
tests.run("*.py")
