# -*- python -*-
Import("env")
import lsst.SConsUtils as scons

env.CheckSwig("python", ilang="c++", includedProducts="mwi fw")

env.LoadableModuleIncomplete("_detectionLib", Split("detectionLib.i"),
                             LIBS=env.getlibs("vw fw detection"))
