# -*- python -*-
Import("env")
import lsst.SConsUtils as scons

env.CheckSwig("python", ilang="c++", includedProducts="mwi fw")

#env.LoadableModuleIncomplete("_imageprocLib", Split("imageprocLib.i"),
#                             LIBS=env.getlibs("vw fw imageproc"))
